### ISSUE TITLE
Rule numbering is wrong for rule 1.2.32

### ISSUE THREAD

**Issue by 111andre111** [elastic/csp-security-policies#136]
Looking to rule 1.2.32 the numbering of the rule is wrong.
https://github.com/elastic/csp-security-policies/blob/main/bundle/compliance/cis_k8s/rules/cis_1_2_32

I had a look to the CIS PDF and I have seen the rule should be 1.2.31 can we please correct that please?
![Screenshot 2022-10-17 at 17 22 59](https://user-images.githubusercontent.com/48132449/196218364-f10f7974-f8b0-4c82-b32d-c78af3cb0b44.png)

A second issue I had is that while trying to mitigate this issue with api server by adding the flag I ended up with errors like that:
`Cipher suite  TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA not supported or doesn't exist`

Turns out the whole mitigation would be that it needs added the flag that TLS version minimum should be TLSv1.2.
Maybe we could mention the flag in the rule content:
`--tls-min-version=VersionTLS12`

**Comment by tinnytintin10** [comment]
Right! Thanks for pointing this out.

@oren-zohar, I don't think we track the minor versions of a benchmark (1.0.0, 1.0.1, etc.) is this metadata we can easily include to reduce user confusion like this in the future?

**Comment by oren-zohar** [comment]
>  @oren-zohar, I don't think we track the minor versions of a benchmark (1.0.0, 1.0.1, etc.) is this metadata we can easily include to reduce user confusion like this in the future?

We track the full benchmark version in every rule, for example, here you can see it in one of the RKS rules we implemented:
https://github.com/elastic/csp-security-policies/blob/1b281f2a4039bd687a9629afc962b982c02eaf4f/bundle/compliance/cis_eks/rules/cis_2_1_1/data.yaml#L81

**Comment by oren-zohar** [comment]
The rule description and number are now auto-generated from the [CIS benchmark files](https://github.com/elastic/csp-security-policies/tree/main/dev/input)
https://github.com/elastic/csp-security-policies/blob/11e3032cb4223b8b64fc7637c2e3b908ca388f31/bundle/compliance/cis_k8s/rules/cis_1_2_32/data.yaml#L3
