### ISSUE TITLE
Create CIS AWS rules templates

### ISSUE THREAD

**Issue by uri-weisman** [elastic/csp-security-policies#142]
**Motivation**

Create the rules templates that will be presented in Kibana.

**Definition of done**

- [ ] Get the newest CSV version of the CIS benchmark.
- [ ] Use the [generator](https://github.com/elastic/csp-security-policies/tree/main/cis_policies_generator) to generate the policy metadata.
- [ ] Review metadata for mistakes.

**Before closing this ticket**
- [ ] Reference to tech-debts that shall be solved as we move forward

**Comment by oren-zohar** [comment]
- Closed by: https://github.com/elastic/integrations/pull/5054
