### ISSUE TITLE
Create the IAM Rego rules

### ISSUE THREAD

**Issue by uri-weisman** [elastic/csp-security-policies#143]
Implement the automated rules of section 1 of the "CIS AWS" benchmark.

- [x] 1.4 Ensure no 'root' user account access key exists 
- [x] 1.5 Ensure MFA is enabled for the 'root' user account
- [x] 1.6 Ensure hardware MFA is enabled for the 'root' user account
- [x] 1.7 Eliminate the use of the 'root' user for administrative and daily tasks
- [x] 1.8 Ensure IAM password policy requires a minimum length of 14 or greater
- [x] 1.9 Ensure IAM password policy prevents password reuse
- [x] 1.10 Ensure multi-factor authentication (MFA) is enabled for all IAM users that have a console password
- [x] 1.11 Do not setup access keys during initial user setup for all IAM users that have a console password
- [x] 1.12 Ensure credentials unused for 45 days or greater are disabled
- [x] 1.13 Ensure there is only one active access key available for any single IAM user
- [x] 1.14 Ensure access keys are rotated every 90 days or less
- [ ] 1.15 Ensure IAM Users Receive Permissions Only Through Groups
- [ ] 1.16 Ensure IAM policies that allow full "*:*" administrative privileges are not attached 
- [ ] 1.17 Ensure a support role has been created to manage incidents with AWS Support
- [ ] 1.19 Ensure that all the expired SSL/TLS certificates stored in AWS IAM are removed
- [ ] 1.20 Ensure that IAM Access analyzer is enabled for all regions

**Comment by oren-zohar** [comment]
There are still a few rules to implement, re-opening

**Comment by uri-weisman** [comment]
Follow-up task to implement the remaining rules:
- https://github.com/elastic/csp-security-policies/issues/178
