### ISSUE TITLE
Implement the Logging rules in the AWS CIS benchmark

### ISSUE THREAD

**Issue by uri-weisman** [elastic/csp-security-policies#147]
Implement the automated rules of section 3 of the "CIS AWS" benchmark:
- [x] 3.1 Ensure CloudTrail is enabled in all regions.
- [x] 3.2 Ensure CloudTrail log file validation is enabled
- [x] 3.3 Ensure the S3 bucket used to store CloudTrail logs is not publicly accessible
- [x] 3.4 Ensure CloudTrail trails are integrated with CloudWatch Logs
- [ ] ~~3.5 Ensure AWS Config is enabled in all regions~~ (8.8)
- [x] 3.6 Ensure S3 bucket access logging is enabled on the CloudTrail S3 bucket
- [x] 3.7 Ensure CloudTrail logs are encrypted at rest using KMS CMKs
- [ ] ~~3.8 Ensure rotation for customer created symmetric CMKs is enabled~~ (8.8)
- [x] 3.9 Ensure VPC flow logging is enabled in all VPCs
- [x] 3.10 Ensure that Object-level logging for write events is enabled for S3 bucket
- [x] 3.11 Ensure that Object-level logging for read events is enabled for S3 bucket
- [x] Implement unit tests to ensure rules work as expected.

Related Tasks:

- https://github.com/elastic/csp-security-policies/pull/180

**Comment by olegsu** [comment]
I will take rule 3.1 
- [ ] 3.1 Ensure CloudTrail is enabled in all regions (Automated)

**Comment by uri-weisman** [comment]
Rules 3.5 and 3.8 will be implemented as part of the following tasks:
- https://github.com/elastic/csp-security-policies/issues/189
- https://github.com/elastic/csp-security-policies/issues/188
