### ISSUE TITLE
Implement the Networking rules part of the AWS CIS benchmark

### ISSUE THREAD

**Issue by uri-weisman** [elastic/csp-security-policies#149]
- [ ] Implement the automated rules of section 5 of the "CIS AWS" benchmark
- [ ] Implement unit tests to ensure rules work as expected.

** Make sure to re-use relevant implemented audit functions

**Comment by olegsu** [comment]
Rules to implement
- [ ] 5.1 Ensure no Network ACLs allow ingress from 0.0.0.0/0 to remote server administration ports 
- [ ] 5.2 Ensure no security groups allow ingress from 0.0.0.0/0 to remote server administration ports
- [ ] 5.3 Ensure no security groups allow ingress from ::/0 to remote server administration ports
- [ ] 5.4 Ensure the default security group of every VPC restricts all traffic

**Comment by oren-zohar** [comment]
There are still a few rules to implement
