### ISSUE TITLE
Migrate Template/Metadata generator to python

### ISSUE THREAD

**Issue by oren-zohar** [elastic/csp-security-policies#165]
**Motivation**
Currently, we have an old script in TS that was implemented by Kanfer. This script is hard to maintain and has some undocumented assumptions. This led to many discrepancies in our benchmarks metadata, and as a result also in the templates.

**Definitaiton of done**
- [x] Migrate Metadata generator - https://github.com/elastic/csp-security-policies/pull/160
- [x] Migrate Templates generator - https://github.com/elastic/csp-security-policies/pull/172
- [x] Add CI step to enforce consistent metadata - https://github.com/elastic/csp-security-policies/pull/166

**Comment by ofiriro3** [comment]
Hi brother :) 

Please don't forget to remove the `muted` and `enabled` fields from the rule generator.
I am attaching the closed PR:

- https://github.com/elastic/csp-security-policies/pull/163
