### ISSUE TITLE
Implement CIS AWS RDS rule 2.3.3

### ISSUE THREAD

**Issue by ari-aviran** [elastic/csp-security-policies#192]
Implement the following AWS CIS rule:

- [x] Implement CIS AWS rule 2.3.3 - Ensure that public access is not given to RDS Instance
- [x] Implement required fetching logic in `cloudbeat`

**Comment by oren-zohar** [comment]
![image](https://github.com/elastic/csp-security-policies/assets/85433724/6351baf6-4cbf-40c6-b6dd-9b1db63389cb)
