### ISSUE TITLE
Implement CIS AWS S3 rule 2.1.5

### ISSUE THREAD

**Issue by ari-aviran** [elastic/csp-security-policies#194]
Implement the following AWS CIS rule:

- [x] Implement CIS AWS rule 2.1.5 - Ensure that S3 Buckets are configured with 'Block public
access (bucket settings)'
- [x] Implement required fetching logic in `cloudbeat`

**Comment by opauloh** [comment]
QA Review:

I couldn't see any findings for this rule on the Findings page, and also I don't see it on the Benchmarks rule page:

Integration version: v1.3.0-preview7
Elastic Stack version: 8.8


![Image](https://user-images.githubusercontent.com/19270322/235755997-39515d0a-f47f-4ee7-9b72-6797beef4ff0.png)



![Image](https://user-images.githubusercontent.com/19270322/235756111-441f9365-ea2e-4c2d-acb6-b2f1f14e162e.png)




![Image](https://user-images.githubusercontent.com/19270322/235756171-2096f72d-dc74-4586-8a0c-1403c1421e64.png)

I'm reopening the issue, but feel free to close it if that's the intended behaviour

**Comment by uri-weisman** [comment]
QA Review:

Rule's template appears on the benchmark page but I could not observe any findings related to rule 2.1.5.

<img width="1908" alt="Screenshot 2023-05-14 at 12 35 04" src="https://github.com/elastic/csp-security-policies/assets/68195305/996ec5b1-0325-4229-8ddc-ee9be709cb68">

**Comment by oren-zohar** [comment]
@ari-aviran I'm re-opening this

**Comment by ari-aviran** [comment]
Verified as fixed in 8.8-SNAPSHOT (BC5 had an old cloudbeat artifact, a new BC will be built soon):

<img width="1840" alt="image" src="https://github.com/elastic/csp-security-policies/assets/94899776/90ce4ce6-dd7c-4c83-8470-d867b67e7ec5">
