### ISSUE TITLE
s3 data adapter produces rego errors 

### ISSUE THREAD

**Issue by tinnytintin10** [elastic/csp-security-policies#198]
I noticed that one of our rules for s3 buckets produces some errors during evaluation:

![Screen Shot 2023-02-22 at 09 56 41](https://user-images.githubusercontent.com/53792284/220660280-c2fe6b36-e8f6-45ac-8f5f-7fcdbbbea10a.png)

cc @uri-weisman @oren-zohar

**Comment by kfirpeled** [comment]
1. verify cloudbeat does not produce errors
