### ISSUE TITLE
[CIS AWS] Rule 1.12 fail when a new created IAM user didn't access console

### ISSUE THREAD

**Issue by uri-weisman** [elastic/csp-security-policies#202]
### Describe the bug

Rule 1.12 fail when evaluating a newly created IAM user that didn't access the console.

### Preconditions
Run an 8.7 elastic agent with a CSPM integration.

### To Reproduce

Write the exact actions one should perform in order to reproduce the bug.
1. Create an IAM user with an active access key.
2. Don't access the AWS console.
3. AWS CIS Rule 1.12 will fail.

### Expected behavior
The rule should pass if the console password has changed in the last 45 days ([Rego code](https://github.com/elastic/csp-security-policies/blob/26b5e7d44d1c6fbc6baa1e5a255434f09cbaff78/bundle/compliance/policy/aws_iam/validate_credentials.rego#L31-L38)).

The benchmark refers to a case where the password wasn’t used as `No_Information` while the AWS SDK actually returns `no_information` - this mismatch cause us to fail in the evaluation.

**Resource**:
```
"resource": {
    "sub_type": "aws-iam-user",
    "name": "cspm_testing",
    "raw": {
      "last_access": "no_information",
      "attached_policies": [
        {
          "PolicyArn": "arn:aws:iam::aws:policy/SecurityAudit",
          "PolicyName": "SecurityAudit"
        }
      ],
      "password_enabled": true,
      "mfa_active": false,
      "name": "cspm_testing",
      "arn": "arn:aws:iam::887624222702:user/cspm_testing",
      "inline_policies": [],
      "access_keys": [
        {
          "last_access": "2023-03-08T11:09:00+00:00",
          "has_used": true,
          "active": true,
          "rotation_date": "2023-03-07T16:36:06+00:00"
        },
        {
          "last_access": "N/A",
          "has_used": false,
          "active": false,
          "rotation_date": "N/A"
        }
      ],
      "password_last_changed": "2023-03-02T15:01:41+00:00"
    },
    "id": "arn:aws:iam::887624222702:user/cspm_testing",
    "type": "identity-management"
  }
```

**Comment by Omolola-Akinleye** [comment]
Status Update: I deployed an  8.7 Deployment and installed cspm with elastic agent. I receive error unable to find. I remember we change data view pattern in 8.8. However, I recieve "No indices match "logs-cloud_security_posture.findings-*"
 

![Image](https://user-images.githubusercontent.com/17135495/235717904-6f363276-592e-4a82-9500-3641c049669d.png)

**Comment by Omolola-Akinleye** [comment]
I need to deploy with 8.8 instead of 8.7. Updated ticket and I will create a new IAM user with 8.8.

**Comment by Omolola-Akinleye** [comment]
Navigate to Integrations -> Security Posture Management ->  Assets -> Findings and apply filter `rule.benchmark.rule_number :"1.12" and resource.id : "arn:aws:iam::704479110758:user/iam-new-user-cspm-8-7-test"`
 
![Image](https://user-images.githubusercontent.com/17135495/235940669-80688501-204a-4f49-b21d-61bf61c25988.png)
