### ISSUE TITLE
Implement IAM rule 1.17: Ensure a support role has been created to manage incidents with AWS Support

### ISSUE THREAD

**Issue by orestisfl** [elastic/csp-security-policies#220]
Split from https://github.com/elastic/csp-security-policies/issues/178

**Comment by opauloh** [comment]
QA Review:

I can see the rule attached to a finding on the Findings page. However, I don't see the rule on the Benchmarks page. 

Integration version: v1.3.0-preview7
Elastic Stack version: 8.8


![Image](https://user-images.githubusercontent.com/19270322/235760007-65fdb484-26d9-4a33-bf2c-622db2e16724.png)



![Image](https://user-images.githubusercontent.com/19270322/235760089-8ec3505f-eecd-4a3f-a8d0-55b519543e18.png)



![Image](https://user-images.githubusercontent.com/19270322/235760037-c3aa6399-2932-4dd1-9e81-f733cce74ff1.png)



I'm reopening the issue, but feel free to close it if that's the intended behaviour.

**Comment by oren-zohar** [comment]
Verified on BC3:


![Image](https://github.com/elastic/csp-security-policies/assets/85433724/59087dd9-e7f7-43eb-b09e-0d99dcff7411)
