### ISSUE TITLE
Implement IAM rule 1.19: Ensure that all the expired SSL/TLS certificates stored in AWS IAM are removed

### ISSUE THREAD

**Issue by orestisfl** [elastic/csp-security-policies#221]
Split from https://github.com/elastic/csp-security-policies/issues/178

**Comment by opauloh** [comment]
QA Review:

I see the rule attached to a finding on the Findings page. However, I don't see it on the Benchmarks page



![Image](https://user-images.githubusercontent.com/19270322/235758335-cb3003a9-b5a7-45a8-a4ac-9552d9e1a7b4.png)




![Image](https://user-images.githubusercontent.com/19270322/235758178-8802c2b8-a478-4fcc-b08d-9f4c555a923d.png)



![Image](https://user-images.githubusercontent.com/19270322/235758282-29e37334-3201-4de8-b09d-cda64b4a9a56.png)



Integration version: v1.3.0-preview7
Elastic Stack version: 8.8

I'm reopening the issue, but feel free to close it if that's the intended behaviour.

**Comment by oren-zohar** [comment]
Verified:

![Image](https://github.com/elastic/csp-security-policies/assets/85433724/2ec5778e-9f95-4cec-a530-fbd006565ae7)
