### ISSUE TITLE
Implement IAM rule 1.20: Ensure that IAM Access analyzer is enabled for all regions

### ISSUE THREAD

**Issue by orestisfl** [elastic/csp-security-policies#222]
Split from https://github.com/elastic/csp-security-policies/issues/178

**Comment by Omolola-Akinleye** [comment]
@orestisfl Do you have steps to reproduce this rule `1.20`?  I  don't see the IAM rule `1.20` when I install CSPM with CIS AWS.

**Comment by Omolola-Akinleye** [comment]
Okay  thank you for notifying me. How do I test this task `Ensure that IAM Access analyzer is enabled for all regions` for `1.20`?

**Comment by Omolola-Akinleye** [comment]
Sorry @orestisfl Nevermind. My mistake, I applied the wrong KQL query filters. Thanks for the input!

**Comment by kfirpeled** [comment]
@Omolola-Akinleye can you please verify it exists in the benchmark?
see an example here: https://github.com/elastic/csp-security-policies/issues/192#issuecomment-1531957605
