### ISSUE TITLE
 Implement IAM rule 1.16: Ensure that IAM Access analyzer is enabled for all regions

### ISSUE THREAD

**Issue by orestisfl** [elastic/csp-security-policies#223]
Split from https://github.com/elastic/csp-security-policies/issues/178

**Comment by orestisfl** [comment]
@Omolola-Akinleye Are you referring to 1.16 or 1.20?

**Comment by Omolola-Akinleye** [comment]
Sorry Rule `1.16`

**Comment by Omolola-Akinleye** [comment]
Sorry @orestisfl  nevermind. I applied the wrong search query filter.

**Comment by Omolola-Akinleye** [comment]
Fixed verifed. Navigate to `Findings`-> `Configuartions` and apply search filter `rule.benchmark.rule_number :"1.16"`

**Comment by kfirpeled** [comment]
@Omolola-Akinleye can you please verify it exists in the benchmark?
see an example here: https://github.com/elastic/csp-security-policies/issues/192#issuecomment-1531957605

**Comment by orestisfl** [comment]
See https://github.com/elastic/integrations/pull/6067
