### ISSUE TITLE
CIS AWS rule number 2.1.5 does not generate findings

### ISSUE THREAD

**Issue by uri-weisman** [elastic/csp-security-policies#233]
### Describe the bug
The rule does not generate any findings.

### Preconditions
CSPM + 8.8 (BC3) env

### To Reproduce
1. Install the CSPM integration and notice that no findings related to rule 2.1.5 are being generated.

**Screenshots**
<img width="1908" alt="Screenshot 2023-05-14 at 12 35 04" src="https://github.com/elastic/csp-security-policies/assets/68195305/808abfe4-a527-4afd-a61d-02048801035d">

**Desktop (please complete the following information):**
 - Kibana Version: VERSION: 8.8.0, BUILD: 62994, COMMIT: 85b22d307ab93fca95c1698ede4cb61d85f3d314
 - Endpoint Version:
 - Other Version:

Related: 
- https://github.com/elastic/csp-security-policies/issues/194

**Comment by ari-aviran** [comment]
Verified as fixed in 8.8-SNAPSHOT (BC5 had an old cloudbeat artifact, a new BC will be built soon):

<img width="1840" alt="image" src="https://github.com/elastic/csp-security-policies/assets/94899776/90ce4ce6-dd7c-4c83-8470-d867b67e7ec5">
