### ISSUE TITLE
[CIS GCP] Implement IAM service rules

### ISSUE THREAD

**Issue by uri-weisman** [elastic/csp-security-policies#239]
### Definition of done
Implement the following rules:
- [ ] 1.4 Ensure That There Are Only GCP-Managed Service Account Keys for Each Service Account
- [ ] 1.5 Ensure That Service Account Has No Admin Privileges
- [ ] 1.6 Ensure That IAM Users Are Not Assigned the Service Account User or Service Account Token Creator Roles at Project Level
- [ ] 1.7 Ensure User-Managed/External Keys for Service Accounts Are Rotated Every 90 Days or Fewer
- [ ] 1.8 Ensure That Separation of Duties Is Enforced While Assigning Service Account Related Roles to Users
- [ ] 1.11 Ensure That Separation of Duties Is Enforced While Assigning KMS Related Roles to Users

The following manual rules are considered critical according to product's prioritization, In case it's possible try to find a way to implement those rules:

- [ ] 1.2 Ensure that Multi-Factor Authentication is 'Enabled' for All Non-Service Accounts
- [ ] 1.3 Ensure that Security Key Enforcement is Enabled for All Admin Accounts

### Related tasks/epics
- https://github.com/elastic/cloudbeat/issues/990

**Comment by orouz** [comment]
closed in favour of https://github.com/elastic/security-team/issues/6179
