### ISSUE TITLE
[CIS GCP] Implement log storage rules

### ISSUE THREAD

**Issue by uri-weisman** [elastic/csp-security-policies#250]
### Definition of done

Implement the following rules:
- [ ] 2.2 Ensure That Sinks Are Configured for All Log Entries
- [x] 2.3 Ensure That Retention Policies on Cloud Storage Buckets Used for Exporting Logs Are Configured Using Bucket Lock

### Related tasks/epics
- https://github.com/elastic/cloudbeat/issues/1000

**Comment by orouz** [comment]
these rules are tricker to implement: 
- rule 2.2 
   -  requires evaluating all sinks and ensuring at least 1 has an empty filter:
  > Ensure there is at least one sink with an empty Inclusion filter.
  
     and we currently send each sink as an asset. 
   - also requires checking each sink's `destination` (usually a bucket) actually exists, which i guess means making an http request which would be new to our rego policies and probably not something we'd like to do. 

- rule 2.3
   - requires getting all sinks ([logging.googleapis.com/LogSink](https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.sinks)) and checking for retention policy and locked buckets ([logging.googleapis.com/LogBucket](https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.locations.buckets)), and currently we can only send each as a separate asset. we would probably need to use a [different](https://github.com/elastic/cloudbeat/blob/63e2f34ac143a5d56c60597f581bb694c8478edb/resources/providers/gcplib/inventory/provider.go#L85C1-L85C1) assets inventory sdk method to accomplish this.

**Comment by uri-weisman** [comment]
will be handled as part of https://github.com/elastic/csp-security-policies/issues/305
