### ISSUE TITLE
[CIS GCP] Implement rule 2.3

### ISSUE THREAD

**Issue by uri-weisman** [elastic/csp-security-policies#301]
Implement the following rule:
- [ ] 2.3 Ensure That Retention Policies on Cloud Storage Buckets Used for Exporting Logs Are Configured Using Bucket Lock

**Comment by kfirpeled** [comment]
- verify rule generates passed and failed findings according to the benchmark and environment

**Comment by Omolola-Akinleye** [comment]
Rule generate passed and failed findings

![Image](https://github.com/elastic/csp-security-policies/assets/17135495/07168dc1-25c5-41cc-82d4-58a7220ab7c2)

**Comment by Omolola-Akinleye** [comment]
Verified 2.3 generates passed and failed findings
![Image](https://github.com/elastic/csp-security-policies/assets/17135495/867e9aa3-e96f-4a70-a2e5-255ce5920a39)
